[Interface]
PrivateKey = <YOUR_WG_CLIENT_PRIVATE_KEY>
Address = 10.66.66.2/24
DNS = 10.66.66.1
MTU = 1360

[Peer]
PublicKey = <YOUR_WG_SERVER_PUBLIC_KEY>
# Connects to local wstunnel client which forwards over TLS TCP port 8080
Endpoint = 127.0.0.1:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 15
